weights: runs/train/pets_others/exp_20210930_5s/weights/best.pt
cfg: models/yolov5s_pets_others.yaml
data: data/pets_others.yaml
hyp: data/hyp.finetune_pets.yaml
epochs: 200
batch_size: 96
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: /vinbrain/thanh/toanhm1/yolov5/runs/train/pets_others
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
recipe: recipes/yolov5s.pruned.md
disable_ema: false
world_size: 1
global_rank: -1
save_dir: !!python/object/apply:pathlib.PosixPath
- /
- vinbrain
- thanh
- toanhm1
- yolov5
- runs
- train
- pets_others
- exp
total_batch_size: 96
